### ISSUE TITLE
Ctrl-S should save the paste instead of the page.

### ISSUE THREAD

**Issue by uroboro** [DHowett/ghostbin#13]
Ghostbin should trap said key combination and prevent the save file prompt from showing.

[DH: Edited the title to be clearer.]

**Comment by Hekter** [comment]
There aren't any key combination shortcuts on Ghostbin so control-s shouldn't be being pushed in the first place, realistically. Most sites don't suppress control-s, so unless Ghostbin starts getting keyboard shortcuts I don't see much reason to block this behavior.

**Comment by uroboro** [comment]
I don't see how **not having keyboard shortcuts** is a reason for **not having keyboard shortcuts**.
As for the other reason, suppressing would make sense in this context as one is trying to save the paste as one would with the save button, **not** with the save prompt to have a local copy of the website page. Saying that most sites don't do that isn't much of a reason to do things differently, like [how ghostbin exists to do what other paste services don't](https://ghostbin.com/about).

**Comment by Hekter** [comment]
Your original suggestion said nothing about adding keyboard shortcuts, just suppressing control-s from spawning the default browser activity. I agree that some keyboard shortcuts would be good for power users.

**Comment by uroboro** [comment]
It's in the title

**Comment by DHowett** [comment]
Accepted & fixed in 9f47cfb
