### ISSUE TITLE
Administration Promotion

### ISSUE THREAD

**Issue by Hekter** [DHowett/ghostbin#29]
As of now the interface to promote users to administrators is decidedly obtuse, especially for those that install Ghostbin themselves. Maybe we can make something akin to the Grant interface on the Admin Panel? Plus better documentation for the initial setup admin, as well as a way to demote users.

Maybe... send user a link which will get their userID (similar to granting), then the admin can put that into a tool with an identifying name so that the new admin can be demoted/removed later at a panel without blindly trying to work with the long user ID strings.

**Comment by DHowett** [comment]
Wait, isn't this done?

**Comment by DHowett** [comment]
The other things should be in their own issue :)
