### ISSUE TITLE
Fork an existing paste

### ISSUE THREAD

**Issue by BHSPitMonkey** [DHowett/ghostbin#31]
(Oops, accidentally submitted without writing the description)

I propose a button in the UI to create a new paste based on the one you're viewing. The button could be called "Fork", "Copy", or "Duplicate", and use the appropriate iconography to match the name.

After clicking, you would see the normal "New paste" UI but with the referenced paste ID's contents and language pre-loaded. (Maybe preselect the expiration period to match as well; Not sure how important that would be.)

I don't think it's necessary to keep track of which pastes are forks of which other pastes (e.g. to display a "Forked from xyzyx" link on the new paste somewhere in the UI).

Thoughts? If you're a fan of this spec but don't have the time, I'm willing to take a stab at the PR.

**Comment by uroboro** [comment]
See [issue #1](https://github.com/DHowett/ghostbin/issues/1).

**Comment by BHSPitMonkey** [comment]
@uroboro I'm not seeing the connection.

**Comment by uroboro** [comment]
You are right. I meant to point to [issue #2](https://github.com/DHowett/ghostbin/issues/2).

**Comment by Hekter** [comment]
This is actually something I was working on here: https://github.com/Hekter/ghostbin/tree/iss4 [Yes, I realize it has nothing to do with iss4]. The backend is functioning [pastes remember their parents and children] but I was having some serious difficulty coming up with a UI that allowed the administrator-side to deal with removing pastes that repeated the same content over and over again that needed to be removed.

This is definitely something we are aware people want, and implementing is relatively simple, but it's dealing with toxic pastes that tends to be the tricky part.

**Comment by DHowett** [comment]
Dupe to #2.
