### ISSUE TITLE
Install Documentation?

### ISSUE THREAD

**Issue by khionu** [DHowett/ghostbin#32]
I apologize if I just missed where you have it, but if you could give me a LS;DR plus requirements, that would be very much appreciated. I saw someone use your own copy of this and I fell in love with its simple design, it's what I've been looking for in a paste service.

**Comment by uroboro** [comment]
This is a duplicate of #27.

**Comment by Hekter** [comment]
Hi khionu! Thanks for checking Ghostbin out =]

I've written a really simple guide here on installing Ghostbin for the time being: https://ghostbin.com/paste/xpymc that worked for me getting it set up just now from scratch.

@DHowett and I are discussing how to properly document this in the future as we are aware that it's not the easiest thing to install.

**Comment by khionu** [comment]
I apologize for the duplicate, I did a quick check via searching keywords but I didn't see anything.

@Hekter thank you :smile_cat: I'm sure it can't be more of a pain than GitLab, and I'd be willing to go through what I need to for it, regardless.

**Comment by khionu** [comment]
Forgive me, I've never worked with anything that used GO, so I'm not exactly sure how to troubleshoot this, but my syntax highlighting isn't working. I did install Pygment, though it wasn't straight-forward at all, there were things missing that I had to install manually in Python, etc, but... not exactly sure how to continue troubleshooting this....

**Comment by Hekter** [comment]
Hi Khionu, apologies for the ambiguity! I haven't had a lot of time this week to buffing out the rough edges of this project but I did figure out the CSS issue. I was missing this (I forgot to test it when I wrote the instructions--my apologies!) so I have edited the install steps on https://ghostbin.com/paste/xpymc to include it. The easy answer is to grab the on we have already generated :)

**Comment by khionu** [comment]
No worries. I've loved GhostBin so far, and I've been busy enough where I haven't been too worried over this, so not a big deal to me :) Have had a lot of people complimenting the interface, it's very nice. Only thing I've seen lacking is an admin interface... I've seen reference to one in the Issues, but haven't figured out how to access it?

**Comment by khionu** [comment]
No worries. It's been worth the wait, and I haven't been idle enough to worry :) I do love the interface, 100% what I've wanted from other pastes, but my only concern is that there appears to be an admin panel that I can't access? I've seen references to it in other issues, plus I did see mention of it in the source, but I'm not fluent enough in Go to have gotten the information I needed..

**Comment by DHowett** [comment]
Hey Khionu!
I'm glad you're sticking with Ghostbin even though it's pretty terrible to
set up. In the latest couple commits, ghostbin will automatically promote
the first user created to Admin. You'll have to update and trash your
accounts/ folder, and make a new account.

If that's not tenable, we can look at releasing an inplace promotion tool!

**Comment by Hekter** [comment]
Hi Khionu,

The latest few commits that we worked on this weekend help grant you admin
panel access. Unfortunately you'll need to download the latest version and
rebuild (and make sure you delete everything in your /accounts folder) but
then you'll have Admin access as the first account ever created.

Then you can access the Admin panel at localhost:8080/admin . There aren't
a lot of options yet--this panel is for promoting other users to Admin and
managing reports.

Another hidden page is /stats which will tell you the memory usage, how
many cached pastes, expiring pastes, and uptime. Don't need to be Admin to
check that out.

**Comment by khionu** [comment]
I can literally say it's everything other pastes have lacked, in my personal search. Given I have no pastes worth keeping, really, just some outdated versions of a bot, and a sample config file that I still have, I'm not concerned. I'll happily rebuild, it's worth the hassle.

For better or worse, it takes a lot for a WIP program to get Anonymous's attention. It's a beautiful interface. Classier than Pastebin, doesn't do that highly inaccurate guessing like Hastebin (and that interface is stylish, but doesn't have flow), the other, smaller pastes are some combination of horrible/no syntax highlighting, horrible install glitches, bad space management, and misc gui flaws.

Ghostbin is dark themed, a personal perk, because I find bright backgrounds harsh. It allows you to manually pick your syntax. Good space management, simple but effective GUI. Love the Mozilla Login feature. Definitely worth it.

**Comment by khionu** [comment]
Sorry, to keep at an old issue, just a small question.... I'm using the Paste in your previous comment to reinstall (different VM), but the Official CSS is 404ing? I mean, I can grab it from my current install, but I was just wondering if that was an issue, or whatnot
