### ISSUE TITLE
Admin Permissions

### ISSUE THREAD

**Issue by JoshuaDoes** [DHowett/ghostbin#33]
Hi,

Since the recent outbreak in #OpParis by Anonymous, I decided to join them in the fight and all that fun stuff and I found that they've been using GhostBin to host their content anonymously. I decided I'd clone the project to run it on my VPS, however I am having an issue figuring out how to give administrative permissions to a user. I've been searching the source code left and right, and I've even run a grep recursive search on the entire directory for permissions, but I can't find it.

Any help would be appreciated.

Thanks,
JoshuaDoes

**Comment by DHowett** [comment]
Hey!

As of the latest couple of commits, Ghostbin will automatically promote the first ever user account to have Admin privileges.

-d

**Comment by JoshuaDoes** [comment]
Thank you :D

**Comment by DHowett** [comment]
Closing this out since it's done; mind reopening it if it's still an issue?
Thanks!

**Comment by JoshuaDoes** [comment]
I just got the notifications for this. It's no longer an issue, thanks!

On Tue, May 10, 2016 at 12:22 PM, Dustin L. Howett <notifications@github.com
