### ISSUE TITLE
Code repository Issue

### ISSUE THREAD

**Issue by OhCreative** [DHowett/ghostbin#35]
I am currently setting up my Ghostbin server but it says that it cannot find the import:

`code.google.com/p/go.crypto/scrypt`

I did a little research and the new repository has been moved to:

`golang.org/x/crypto/scrypt`

Any way you could update the imports in the code?

**Comment by DHowett** [comment]
Good catch. Thanks for digging up the correct URL. :)

-- Dustin L. Howett

**Comment by OhCreative** [comment]
@DHowett Also I know this isn't affiliated with ghostbin, but when I'm setting up my server I add this to my sources.list file:

`deb http://ppa.launchpad.net/bzr/ppa/ubuntu trusty main 
deb-src http://ppa.launchpad.net/bzr/ppa/ubuntu trusty main`

and when I redownload my sources, one of the links throws an error, could you help with that? (Sorry I'm new to Ubuntu CLI)

**Comment by OhCreative** [comment]
@DHowett Any helpful other issues or articles for it?
