### ISSUE TITLE
I am unable to login or make a new account.

### ISSUE THREAD

**Issue by Xibster** [DHowett/ghostbin#40]
Try to login and the login box just goes gray. Refreshing the page just resets it the box as blank.
Waiting 6 seconds will have a message pop up saying I was "successfully logged out". Making a new account and logging in via Email is futile.
https://i.imgur.com/BY68bdk.jpg

**Comment by DHowett** [comment]
Thanks for the report. Are you logging in via Persona?

**Comment by DHowett** [comment]
(Persona is being deprecated by the provider, but I don't recall whether it was July or November. If it was July, we're a little too late to migrate. D'oh!)

**Comment by DHowett** [comment]
This was caused by a bad firewall rule on the server.
Thanks for reporting!
