### ISSUE TITLE
The persona.org service has shut down

### ISSUE THREAD

**Issue by privacytoolsIO** [DHowett/ghostbin#58]
Ghostbin is using persona.org but it has shut down:
https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers

**Comment by uroboro** [comment]
You have to switch to password based auth now. Ghostbin has a transition method to automatically transfer ownership of pastes (not sure if that still works due to persona.org being no longer).

**Comment by DHowett** [comment]
Ghostbin has implemented persona migration. I'm on my phone and cannot
provide the number of the (closed) bug tracking its progress.

While persona is still up, which it was last I checked this week, account
migration will be live.

Please migrate if you have not yet done so.

**Comment by DHowett-MSFT** [comment]
Addendum: #44.

**Comment by DHowett** [comment]
Looks like it is now dead.

**Comment by DHowett** [comment]
Persona's been removed from the frontend. I'll provide migration guidance for anyone who missed automated migration soon.
