### ISSUE TITLE
Enable CORS to allow cross-origin requests

### ISSUE THREAD

**Issue by mdxe** [DHowett/ghostbin#60]
Would you consider enabling CORS to allow cross-origin request from another server's javascript?

[enabling CORS](http://enable-cors.org/)

**Comment by uroboro** [comment]
Why do you want this?

**Comment by mdxe** [comment]
To be able to create/edit ghostbins from my webapp on the client's side (using javascript)... the ghostbins would be used to share data across multiple computers.   Github's gists do enable CORS but gists can't be edited without using an account.

**Comment by uroboro** [comment]
> the ghostbins would be used to share data across multiple computers

That sounds like piggybacking on ghostbin to work as a data server for you for free.

**Comment by DHowett** [comment]
I'm not comfortable with this until user and session authentication is tied to a revocable, site-specific auth token. Even then, @uroboro's concern is valid 😜 

#61 should probably have some provision for authentication.
