### ISSUE TITLE
Raw pastes

### ISSUE THREAD

**Issue by P4risAndStuff** [DHowett/ghostbin#64]
Can you actually view pastes in raw form? I try adding /raw after pastes, but I always get a blank white page. I noticed acknowledgement of "/raw" on [this paste](https://ghostbin.com/paste/p3qcy) but I'm not sure what the point of /raw is, is it just for API stuff? If it's not an official feature, it would be nice to see it become one.

**Comment by Hekter** [comment]
Hey P4ris, 

This used to be a feature, but we found that it was being abused and causing an inordinate amount of server load. This should still work for the self-deploy version, but is disabled on the main site.

**Comment by P4risAndStuff** [comment]
@Hekter Thank you for the explanation!
