### ISSUE TITLE
Broken font

### ISSUE THREAD

**Issue by tagener-noisu** [DHowett/ghostbin#65]
Hi, I tried to create a paste with cyrillic characters and there was a problem with a font. Since default font doesn't support cyrillic characters it should fallback to a system monospace font, but it doesn't.
The default CSS rule is: (my browser ignores the 'monospace' part and uses default serif font)
`font-family: 'EnvyCodeRWeb','monospace';`
But it works well when I change it like this:
`font-family: 'EnvyCodeRWeb', monospace;` (without quotes)
According to this https://www.w3.org/TR/CSS2/fonts.html#font-family-prop , you shouldn't use quotes around generic font family names.

You may want to provide a cyrillic font in the future.
https://www.fontsquirrel.com/fonts/fira-mono
http://input.fontbureau.com/info/

**Comment by tagener-noisu** [comment]
I've created a pull request for you that fixes this issue.

**Comment by DHowett** [comment]
Ugh, I was complaining on Hacker News about this exact CSS issue. It's ironic that I was myself bitten by it.

Thanks for the fix.

**Comment by DHowett** [comment]
I'm reopening this to track the use of a font with extended characters. I really like Fira Code nowadays, but it required ligatures and in general might really piss some people off :wink:

**Comment by DHowett** [comment]
Actually, duped to #68.
